# Generated by Django 5.0 on 2024-01-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_mfd_product_stock_count_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, default=2.99, max_digits=10)),
                ('stock_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='app1.product')),
            ],
            options={
                'verbose_name_plural': 'Product variants',
            },
        ),
        migrations.CreateModel(
            name='VariantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='variant.jpg', upload_to='variant_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productvariant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_images', to='app1.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Product Variants',
            },
        ),
    ]
