# Generated by Django 5.0 on 2024-01-16 06:07

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_color_productvariant_variantimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='Images',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.user_directory_path),
        ),
    ]
