# Generated by Django 5.0 on 2024-01-16 06:14

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_productimages_images_productimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product.jpg', null=True, upload_to=app1.models.user_directory_path),
        ),
    ]
